module.exports = {
  Admin: require("./admin"),
  Artikel: require("./artikel"),
  Message: require("./hubungi"),
  Kategori: require("./kategori"),
  Komunitas: require("./komunitas"),
  Psikolog: require("./psikolog"),
  Testimoni: require("./testimoni"),
  Tim: require("./timKami"),
  User: require("./user"),
  Webinar: require("./webinar"),
  Konsultasi: require("./konsultasi"),
  Paket: require("./paket"),
  TestiPsikolog: require("./testiPsikolog"),
  Deteksi: require("./deteksi"),
};
